# Generated by Django 2.1.3 on 2018-12-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_baz'),
    ]

    operations = [
        migrations.AddField(
            model_name='baz',
            name='baz_sillyfield2',
            field=models.CharField(default='my default value', max_length=200),
            preserve_default=False,
        ),
    ]
